---
title: "Combined+selecting+neighborhoods"
author: "Sijian Xuan"
date: "November 23, 2017"
output:
  html_document: default
  pdf_document: default
---
###Read data and set weight, threshold
```{r}
load("../output/web.sp.sim.Rdata")
load("../output/web.entropy.sim.Rdata")
load("../output/web.msd.sim.Rdata")
data1 = web.sp.sim
diag(data1) = 0
data2 = web.entropy.sim
diag(data2) = 0
data3 = web.msd.sim
diag(data3) = 0
# dimension of 3 dataset are all 4151 dimension square matrices.
```
```{r}
hist(data1,30)
hist(data2,30)
hist(data3,30)
```
```{r}
threshold1 = 0.8
threshold2 = 8
threshold3 = 0.25
n = 20 
```
### Standard: larger than threshold and max number of estimator is n.
```{r}
aaa<- function(x,threshold){
  a1<- x[order(-x)][1:n]*(x[order(-x)][1:n]>=threshold)
  a1[a1==0]<- NA
  res<- which(x %in% a1)[1:n]
  return(res)
}
```
####web dataset, spearman
```{r}
data = data1
threshold = threshold1
result = t(apply(data, 1, function(x) aaa(x,threshold)))
value_matrix = matrix(0,dim(result)[1],dim(result)[2])
for(x in 1:4151){
  #4151 is the dimension of 'data'
  for(y in 1:n){
    if(is.na(value_matrix[x,y]) == FALSE){
      value_matrix[x,y] = data1[x,result[x,y]]
    }
  }
}
save(value_matrix, file = "../output/sn_web_sp_n=20_th=0.8.Rdata")
```
####web dataset, entropy
```{r}
data = data2
threshold = threshold2
result = t(apply(data, 1, function(x) aaa(x,threshold)))
value_matrix = matrix(0,dim(result)[1],dim(result)[2])
for(x in 1:4151){
  #4151 is the dimension of 'data'
  for(y in 1:n){
    if(is.na(value_matrix[x,y]) == FALSE){
      value_matrix[x,y] = data1[x,result[x,y]]
    }
  }
}
save(value_matrix, file = "../output/sn_web_entropy_n=20_th=8.Rdata")
```
###web dataset, msd
```{r}
data = data3
threshold = threshold3
result = t(apply(data, 1, function(x) aaa(x,threshold)))
value_matrix = matrix(0,dim(result)[1],dim(result)[2])
for(x in 1:4151){
  #4151 is the dimension of 'data'
  for(y in 1:n){
    if(is.na(value_matrix[x,y]) == FALSE){
      value_matrix[x,y] = data1[x,result[x,y]]
    }
  }
}
save(value_matrix, file = "../output/sn_web_msd_n=20_th=0.25.Rdata")
```
